const express = require('express');
const bcrypt = require('bcryptjs');
const { z } = require('zod');
const Rider = require('../models/rider');
const { generateToken, authMiddleware } = require('../middleware/auth');
const axios = require('axios');

const router = express.Router();
const ML_SERVICE_URL = process.env.ML_SERVICE_URL || 'http://localhost:8000';

// Validation schemas
const registerSchema = z.object({
  name: z.string().min(2).max(100),
  phone: z.string().regex(/^[6-9]\d{9}$/, 'Invalid Indian phone number'),
  city: z.enum(['Mumbai', 'Delhi', 'Bangalore', 'Chennai', 'Pune', 'Hyderabad']),
  zone: z.string().min(2).max(100),
  platform: z.enum(['Swiggy', 'Zomato']),
  avg_weekly_earnings: z.number().min(500).max(20000),
  password: z.string()
    .min(8, 'Password must be at least 8 characters')
    .max(100)
    .regex(/[A-Z]/, 'Password must contain at least one uppercase letter')
    .regex(/[a-z]/, 'Password must contain at least one lowercase letter')
    .regex(/[0-9]/, 'Password must contain at least one number')
    .optional()
});

const loginSchema = z.object({
  phone: z.string().regex(/^[6-9]\d{9}$/),
  password: z.string().optional(),
  otp: z.string().length(6).optional()
});

// POST /api/riders/register
router.post('/register', async (req, res) => {
  try {
    const data = registerSchema.parse(req.body);

    // Check if phone already exists
    const existing = await Rider.findByPhone(data.phone);
    if (existing) {
      return res.status(409).json({ error: 'Phone number already registered' });
    }

    // Hash password
    let passwordToHash = data.password;
    let autoGenerated = false;
    if (!passwordToHash) {
      if (process.env.NODE_ENV === 'production') {
        return res.status(400).json({ error: 'Password is required' });
      }
      passwordToHash = require('crypto').randomBytes(8).toString('hex');
      autoGenerated = true;
    }
    const password_hash = await bcrypt.hash(passwordToHash, 10);

    const rider = await Rider.create({
      name: data.name,
      phone: data.phone,
      city: data.city,
      zone: data.zone,
      platform: data.platform,
      avg_weekly_earnings: data.avg_weekly_earnings,
      password_hash
    });

    // Generate JWT token
    const token = generateToken(rider);

    // Try to get initial score from ML service
    let score = null;
    try {
      const scoreRes = await axios.post(`${ML_SERVICE_URL}/ml/score/rider`, {
        rating: 4.0,
        tenure_months: 0,
        weekly_earnings: data.avg_weekly_earnings,
        claims_6m: 0,
        active_days: 5,
        city: data.city
      }, { timeout: 5000 });
      score = scoreRes.data;
    } catch (mlErr) {
      console.warn('ML service unavailable for initial scoring:', mlErr.message);
    }

    const { password_hash: _pw, ...safeRider } = rider;
    const responsePayload = {
      message: 'Registration successful',
      rider: safeRider,
      token,
      score
    };

    if (autoGenerated && process.env.NODE_ENV !== 'production') {
      responsePayload.demoPassword = passwordToHash;
    }

    res.status(201).json(responsePayload);
  } catch (err) {
    if (err instanceof z.ZodError) {
      return res.status(400).json({ error: 'Validation failed', details: err.errors });
    }
    console.error('Registration error:', err);
    res.status(500).json({ error: 'Registration failed' });
  }
});

// POST /api/riders/login
router.post('/login', async (req, res) => {
  try {
    const data = loginSchema.parse(req.body);

    const rider = await Rider.findByPhoneWithHash(data.phone);
    if (!rider) {
      return res.status(401).json({ error: 'Invalid credentials' });
    }

    // For demo: accept configured OTP check or check password
    if (data.otp) {
      if (!process.env.ALLOW_DEMO_OTP || data.otp !== process.env.ALLOW_DEMO_OTP) {
        return res.status(401).json({ error: 'Invalid credentials' });
      }
    } else if (data.password) {
      const valid = await bcrypt.compare(data.password, rider.password_hash);
      if (!valid) {
        return res.status(401).json({ error: 'Invalid credentials' });
      }
    } else {
      return res.status(400).json({ error: 'Provide OTP or password' });
    }

    const token = generateToken(rider);

    const { password_hash: _pw, ...safeRider } = rider;
    res.json({
      message: 'Login successful',
      rider: safeRider,
      token
    });
  } catch (err) {
    if (err instanceof z.ZodError) {
      return res.status(400).json({ error: 'Validation failed', details: err.errors });
    }
    console.error('Login error:', err);
    res.status(500).json({ error: 'Login failed' });
  }
});

// GET /api/riders/:id/profile
router.get('/:id/profile', authMiddleware, async (req, res) => {
  const requestedId = parseInt(req.params.id);
  if (req.user.id !== requestedId && req.user.role !== 'admin') {
    return res.status(403).json({ error: 'Forbidden' });
  }

  try {
    const rider = await Rider.findById(requestedId);
    if (!rider) {
      return res.status(404).json({ error: 'Rider not found' });
    }

    const { password_hash: _pw, ...safeRider } = rider;
    res.json({ rider: safeRider });
  } catch (err) {
    console.error('Profile fetch error:', err);
    res.status(500).json({ error: 'Failed to fetch profile' });
  }
});

// GET /api/riders/:id/score
router.get('/:id/score', authMiddleware, async (req, res) => {
  const requestedId = parseInt(req.params.id);
  if (req.user.id !== requestedId && req.user.role !== 'admin') {
    return res.status(403).json({ error: 'Forbidden' });
  }

  try {
    const rider = await Rider.findByIdWithScore(requestedId);
    if (!rider) {
      return res.status(404).json({ error: 'Rider not found' });
    }

    // If no score exists, calculate one from ML service
    if (!rider.total_score) {
      try {
        const claims = await Rider.getClaimsCount(rider.id);
        const scoreRes = await axios.post(`${ML_SERVICE_URL}/ml/score/rider`, {
          rating: parseFloat(rider.lifetime_avg_rating) || 4.0,
          tenure_months: rider.tenure_months || 0,
          weekly_earnings: parseFloat(rider.avg_weekly_earnings) || 3000,
          claims_6m: claims,
          active_days: 5,
          city: rider.city
        }, { timeout: 5000 });

        return res.json({
          rider: {
            id: rider.id,
            name: rider.name,
            city: rider.city,
            zone: rider.zone
          },
          score: scoreRes.data
        });
      } catch (mlErr) {
        console.warn('ML service unavailable:', mlErr.message);
        return res.status(503).json({
          rider: {
            id: rider.id,
            name: rider.name,
            city: rider.city,
            zone: rider.zone
          },
          score: null,
          message: 'ML service unavailable'
        });
      }
    }

    res.json({
      rider: {
        id: rider.id,
        name: rider.name,
        city: rider.city,
        zone: rider.zone
      },
      score: {
        total_score: rider.total_score,
        breakdown: {
          rating: rider.rating_score,
          tenure: rider.tenure_score,
          earnings: rider.earnings_score,
          claims: rider.claims_score,
          consistency: rider.consistency_score,
          city_risk: rider.city_risk_score
        },
        premium_pct: rider.premium_pct
      }
    });
  } catch (err) {
    console.error('Score fetch error:', err);
    res.status(500).json({ error: 'Failed to fetch score' });
  }
});

module.exports = router;
